// <auto-generated />
using System;
using Drums.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Drums.Data.Migrations
{
    [DbContext(typeof(DrumsDbContext))]
    [Migration("20200521085306_initial_test")]
    partial class initial_test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Drums.Data.Entities.GradeSpecificSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportCardId")
                        .HasColumnType("int");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReportCardId");

                    b.ToTable("GradeSpecificSetting");
                });

            modelBuilder.Entity("Drums.Data.Entities.LayoutSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportCardId")
                        .HasColumnType("int");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReportCardId");

                    b.ToTable("LayoutSetting");
                });

            modelBuilder.Entity("Drums.Data.Entities.ReportCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReportCards");
                });

            modelBuilder.Entity("Drums.Data.Entities.ReportCardContentSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportCardId")
                        .HasColumnType("int");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReportCardId");

                    b.ToTable("ReportCardContentSetting");
                });

            modelBuilder.Entity("Drums.Data.Entities.GradeSpecificSetting", b =>
                {
                    b.HasOne("Drums.Data.Entities.ReportCard", null)
                        .WithMany("GradeSpecificSettings")
                        .HasForeignKey("ReportCardId");
                });

            modelBuilder.Entity("Drums.Data.Entities.LayoutSetting", b =>
                {
                    b.HasOne("Drums.Data.Entities.ReportCard", null)
                        .WithMany("LayoutSettings")
                        .HasForeignKey("ReportCardId");
                });

            modelBuilder.Entity("Drums.Data.Entities.ReportCardContentSetting", b =>
                {
                    b.HasOne("Drums.Data.Entities.ReportCard", null)
                        .WithMany("ReportCardContentSettings")
                        .HasForeignKey("ReportCardId");
                });
#pragma warning restore 612, 618
        }
    }
}
